{% set name = "pytest-check-meta" %}
{% set version = "2.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/pytest-check/pytest_check-{{ version }}.tar.gz
  sha256: 33d87e28d5e49217f413277e1e0d267cd66c90a85a208944c44312c9c8e4ff74

build:
  number: 0

outputs:
  - name: pytest-check

    build:
      noarch: python
      script: ${PYTHON} -m pip install . -vv --no-deps --no-build-isolation

    requirements:
      host:
        - python {{ python_min }}
        - hatchling
        - pip
      run:
        - python >={{ python_min }}
        - pytest
        - typing-extensions >=4.12.2

    test:
      imports:
        - pytest_check
      requires:
        - pip
        - python {{ python_min }}
      source_files:
        - tests/
        - examples/
        - tox.ini
      commands:
        - pip check
        - pytest -k "not test_max_tb"

  - name: pytest_check

    # Meta-package to the main package, that just installs it
    # it is here to keep-up with the legacy name, containing an
    # underscore ("_") instead of a dash.
    build:
      noarch: generic

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage("pytest-check", exact=True) }}

    test:
      imports:
        - pytest_check
      requires:
        - python {{ python_min }}

about:
  home: https://github.com/okken/pytest-check
  summary: A pytest plugin that allows multiple failures per test.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
    - bskinn
    - anjos
